### ISSUE TITLE
Missing version for spring-core artifact in dependencyManagement

### ISSUE THREAD

**Issue by bikeholik** [spring-cloud/spring-cloud-build#35]
Isn't version missing in spring-core artifact in dependencyManagement section of pom.xml?

I have encountered the problem first when my project was processed by sonar plugin.

Using maven3 I also have a similar error when trying to install the spring-cloud-build project locally:

```
[ERROR] Internal error: org.apache.maven.artifact.InvalidArtifactRTException: For artifact {org.springframework:spring-core:null:jar}: The version cannot be empty. -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.apache.maven.artifact.InvalidArtifactRTException: For artifact {org.springframework:spring-core:null:jar}: The version cannot be empty.
    at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:95)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.apache.maven.artifact.InvalidArtifactRTException: For artifact {org.springframework:spring-core:null:jar}: The version cannot be empty.
    at org.apache.maven.artifact.DefaultArtifact.validateIdentity(DefaultArtifact.java:148)
    at org.apache.maven.artifact.DefaultArtifact.<init>(DefaultArtifact.java:123)
```

If I set a version like below it works fine:

```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-core</artifactId>
                <version>${spring.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>commons-logging</groupId>
                        <artifactId>commons-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by dsyer** [comment]
It works for me with the Maven version we supply in the wrapper (please don't try with any other version).

I'm curious why we need it (the spring-core dependency) at all, since it is managed by Spring Boot. What happens if we just remove it?

**Comment by bikeholik** [comment]
Spring Boot BOM doesn't exclude commons-logging by default, but yes it is managed there

**Comment by stephlag** [comment]
Build fails with maven 3.2.3 but succeeds with the provided latest maven version (3.3.9)

**Comment by spencergibb** [comment]
Any reason to keep this open?

**Comment by stephlag** [comment]
I do not see any as the build is ok with maven 3.3.9

**Comment by dsyer** [comment]
This can actual cause issues with some projects. I have a project with a submodule that uses Spring Cloud and assembly plugin. The assembly fails on a reactor build (from the parent) but succeeds in the child directory, complaining about a missing version for spring-core. Super annoying, and not a known issue as far as I can tell in the assembly plugin.

**Comment by adamzr** [comment]
I'm working with a CI server that only has old versions of Maven. Is there a workaround?

**Comment by bikeholik** [comment]
Back then I had setup a bamboo step that was installing altered spring-cloud-build pom file before executing another step that depended on having this set correctly.

**Comment by dsyer** [comment]
This shouldn't be a problem any more (the parent Pom was restructured in 1.3.2). Why are you building spring cloud projects in such a CI server anyway?
